### PR TITLE
Unable to start service

### PR DESCRIPTION
**Pull request by ggn06awu**
I've been having trouble starting the stock (and other) services, the error seems to relate back to a monq library worker call, it's defaults are lacking type checking, throwing an unhandled error in the process. 

I've proposed a fix (to give a non-null object through to monq). The error I was receiving on boot was:

<pre><code>
2016-11-14T13:28:25.886Z - error: uncaughtException: Cannot read property 'collection' of undefined 
{ date: 'Mon Nov 14 2016 13:28:25 GMT+0000 (GMT)',
  process: 
   { pid: 22254,
     uid: 1000,
     gid: 1000,
     cwd: '/home/mark/WebstormProjects/micro-stock-service/src',
     execPath: '/usr/local/bin/node',
     version: 'v6.3.1',
     argv: 
      [ '/usr/local/bin/node',
        '/home/mark/WebstormProjects/micro-stock-service/src/index.js' ],
     memoryUsage: { rss: 83554304, heapTotal: 70021120, heapUsed: 42986160 } },
  os: 
   { loadavg: [ 1.51904296875, 1.16162109375, 1.67626953125 ],
     uptime: 25044 },
  trace: 
   [ { column: 36,
       file: '/home/mark/WebstormProjects/micro-stock-service/src/node_modules/monq/lib/connection.js',
       function: 'Connection.worker',
       line: 35,
       method: 'worker',
       native: false },
     { column: 25,
       file: '/home/mark/WebstormProjects/micro-stock-service/src/node_modules/microbase/modules/workers/index.js',
       function: 'workers.forEach.job',
       line: 23,
       method: 'forEach.job',
       native: false },
     { column: null,
       file: null,
       function: 'Array.forEach',
       line: null,
       method: 'forEach',
       native: true },
     { column: 11,
       file: '/home/mark/WebstormProjects/micro-stock-service/src/node_modules/microbase/modules/workers/index.js',
       function: 'workers',
       line: 19,
       method: null,
       native: false },
     { column: 65,
       file: '/home/mark/WebstormProjects/micro-stock-service/src/node_modules/microbase/index.js',
       function: 'module.exports',
       line: 65,
       method: 'exports',
       native: false },
     { column: 96,
       file: '/home/mark/WebstormProjects/micro-stock-service/src/index.js',
       function: '',
       line: 1,
       method: null,
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module._compile',
       line: 541,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'module.js',
       function: 'Object.Module._extensions..js',
       line: 550,
       method: 'Module._extensions..js',
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module.load',
       line: 458,
       method: 'load',
       native: false },
     { column: 12,
       file: 'module.js',
       function: 'tryModuleLoad',
       line: 417,
       method: null,
       native: false },
     { column: 3,
       file: 'module.js',
       function: 'Function.Module._load',
       line: 409,
       method: 'Module._load',
       native: false },
     { column: 10,
       file: 'module.js',
       function: 'Module.runMain',
       line: 575,
       method: 'runMain',
       native: false },
     { column: 7,
       file: 'bootstrap_node.js',
       function: 'run',
       line: 352,
       method: null,
       native: false },
     { column: 9,
       file: 'bootstrap_node.js',
       function: 'startup',
       line: 144,
       method: null,
       native: false },
     { column: 3,
       file: 'bootstrap_node.js',
       function: null,
       line: 467,
       method: null,
       native: false } ],
  stack: 
   [ 'TypeError: Cannot read property \'collection\' of undefined',
     '    at Connection.worker (/home/mark/WebstormProjects/micro-stock-service/src/node_modules/monq/lib/connection.js:35:36)',
     '    at workers.forEach.job (/home/mark/WebstormProjects/micro-stock-service/src/node_modules/microbase/modules/workers/index.js:23:25)',
     '    at Array.forEach (native)',
     '    at workers (/home/mark/WebstormProjects/micro-stock-service/src/node_modules/microbase/modules/workers/index.js:19:11)',
     '    at module.exports (/home/mark/WebstormProjects/micro-stock-service/src/node_modules/microbase/index.js:65:65)',
     '    at Object.<anonymous> (/home/mark/WebstormProjects/micro-stock-service/src/index.js:1:96)',
     '    at Module._compile (module.js:541:32)',
     '    at Object.Module._extensions..js (module.js:550:10)',
     '    at Module.load (module.js:458:32)',
     '    at tryModuleLoad (module.js:417:12)',
     '    at Function.Module._load (module.js:409:3)',
     '    at Module.runMain (module.js:575:10)',
     '    at run (bootstrap_node.js:352:7)',
     '    at startup (bootstrap_node.js:144:9)',
     '    at bootstrap_node.js:467:3' ] }
</code></pre>

### CODE REVIEW

**Comment by ncornag** [comment]
Hi. Are you trying the default configuration or are you adding other workers by your own?
Because "it works in my computer" :) And digging into the monq code, when calling `jobs.worker([job.worker])` (line 23 of workers.js), there are no need for the second parameter, the options...
The parameter addition doesn't seems to me harmful at all, but I want to understand why is not working for you.
By the way, the monq version used is 0.3.4, your modules were resolved with the same version, right?

**Comment by ggn06awu** [comment]
Hey! I was using the defaults, off the back of running the run.sh scaffolding example. Then checked out the service directly and tried to spin it up with `node index.js` but same issue.

monq is definitely resolving to 0.3.4. It's a tough one, the following block from monq (as far as i can see) definitely unsafely accesses `options.collection`. 

<pre><code>

/**
* Returns a new {@link Worker}
* @param {string[]|string} queues - list of queue names, a single queue name, or '*' for a universal worker
* @param {Object} options - an object with worker options
*/
Connection.prototype.worker = function (queues, options) {
    var self = this,
        opts;

    if (queues === "*") {
        opts = {universal: true, collection: options.collection || 'jobs' };
        options.universal = true;
        queues = [self.queue('*', opts)];
    } else {
        if (!Array.isArray(queues)) {
            queues = [queues];
        }

        opts = {collection: <strong>options.collection</strong> || 'jobs' };
        var queues = queues.map(function (queue) {
            if (typeof queue === 'string') {
                queue = self.queue(queue, opts);
            }

            return queue;
        });
    }
    return new Worker(queues, options);
};
</code>
</pre>

**Comment by ncornag** [comment]
Got it. The code you are seeing is from the v0.3.5, modified 3 days ago. I will merge your PR (thanks) and update the dependencies, because the workers seems to work fine with the new version.
I'm experimenting with yarn, as it locks the modules version. If you are in trouble again you can also execute  `yarn --pure-lockfile` instead of `npm install`.

**Comment by ggn06awu** [comment]
Apologies, saw `"raw": "monq@^0.3.4": ` and jumped the gun on that reply. You're totally correct - `version": "0.3.5"`

I've put a PR in to their repo accordingly too, might help some others encountering this. 

Thanks for the yarn tip, and a quick "well done", Microbase looks like a great start, just thumbing through it with a view to building something on it.

**Comment by ncornag** [comment]
Thanks for the comment. We have a long way to go and big plans for microbase!

**Pull request merged**
