### PR TITLE
dump config in development mode

### PR DESCRIPTION
**Pull request by amarinso**
add the route "micro:config" to show effective configuration of the service

### CODE REVIEW

**Comment by amarinso** [comment]
I was having errors while contacting the gateway from a running instance outside a docker container....
long story short... I had a bad configuration but was unsure of the "effective" configuration in use

This PR dumps the contents of the nconf object 

It makes it available only when debug is enabled

The route uses the format ***micro:config*** that maybe could be adopted for microbase routes... like for example ***micro:ping***

**Comment by ncornag** [comment]
Great idea!
Question: Why allow the config dump only in debug? It's seems a god starting point for an admin console...
Regarding the naming scheme, the colon symbol is already used as a separator between the service name and the operation name i.e.: `base.services.call({ name: 'catalog:product.info' } ...)`, therefore I would rename those services to  `micro.operationName` like in (`micro.ping`, `micro.config`). Calling those services will be something like `base.services.call({ name: 'catalog:micro.config' } ...)`
Later we could also have `micro.config.info` and `micro.config.update` if we build the console.
Beware that change the ping operation name implies changes in the docker consul image that uses the operation (I can modify it)

**Comment by amarinso** [comment]
It's only in debug because right now is dumping a lot of information about the nodejs environment, not only about the application

nconf seems to have a method to whitelist some of the properties, so it can be the way to make it avaiable to production.

Regarding the naming... we could have a micro service called "micro" for administrative related operations so it could be called like:

`base.services.call({ name: 'micro:ping'})`
`base.services.call({ name: 'micro:config'})`

**Comment by ncornag** [comment]
The ping operation is automagically embedded in every service, that's why you have right now `catalog:ping` and `stock:ping`, to ping a specific service...
The same should happen with `catalog:config` that will dump the catalog service config, opposed to `stock:config` that will dump the stock service config, right?

**Comment by amarinso** [comment]
Oh, it's true.... so maybe we should prepend the `micro.` prefix to avoid operation name collision

**Comment by ncornag** [comment]
You will change the code, right?

**Comment by amarinso** [comment]
Wow, I didn't knew that you can change the code within github itself and it automatically creates the PR!

**Pull request merged**
